name: azcausal

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install azcausal
        run: |
          pip install .
          rm -rf azcausal
      - name: Run Tests
        run: |
          pytest -v --maxfail 1
